services:
  database:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: db

  # web:
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "5433:8000"
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 5432

volumes:
  data: